#DB config details
db:
  password: "![ij6UP3XXjZM=]"
  user: "![c6/KkkNKJ/o=]"
  

sf:
  securityToken: "![JhgrtzUlJd6gpyeuTzym4JupsjX9hy2qCe3TPoeFO7Y=]"
  password: "![2YNZt1lm+MRm7qkhAuEumw==]"
  consumerKey: "![EcXBTeWMMaVCEEi9WUaGSqE09nvQOCXB8A0KkGVWkyZOBaY1+m0B7te3JSWrKUPCfd9wxS9PIB5P3AFn9zrs5pg815nBHF0V3G8dltx78IhdjTzU31pnEA==]"
  consumerSecret: "![/R6rU6BCBm6HSsMJWPKTSd97S0VwGuQdqnnCRpYHdgJfJ7hb/Va5860uD6lVzmQ/95UtFnynjLulyE8DlNQGAyDIjV/aQhK2]"  