sf:
  authURL: "https://login.salesforce.com/services/Soap/u/56.0"
  username: "mulesoftintegration@ntnusa.com"
  tokenEndpoint: "https://ntnconnect.my.salesforce.com/services/oauth2/token"
  
db:
  host: "129.147.16.38"
  port: "1521"
  svc: "jdeorcl.netuenazr.vcnzgqox.oraclevcn.com"
  

http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
