#%RAML 1.0 NamedExample
[
  {
    "IsActive": true,
    "CurrencyIsoCode": "USD",
    "Product2Id": "01tVC000008MHlZYAW",
    "PriceBookId": {
      "id": [
        "01sf4000001ovQBAAY",
        "01sf4000006iq7pAAA",
        "01sf4000006iq7rAAA",
        "01sVC000000pl4vYAA",
        "01sVC000000pl6XYAQ"
      ]
    },
    "UnitPrice": 0
  },
  {
    "IsActive": true,
    "CurrencyIsoCode": "USD",
    "Product2Id": "01tVC000008MHlaYAG",
    "PriceBookId": {
      "id": [
        "01sf4000001ovQBAAY",
        "01sf4000006iq7pAAA",
        "01sf4000006iq7rAAA",
        "01sVC000000pl4vYAA",
        "01sVC000000pl6XYAQ"
      ]
    },
    "UnitPrice": 0
  },
  {
    "IsActive": true,
    "CurrencyIsoCode": "USD",
    "Product2Id": "01tVC000008MHlbYAG",
    "PriceBookId": {
      "id": [
        "01sf4000001ovQBAAY",
        "01sf4000006iq7pAAA",
        "01sf4000006iq7rAAA",
        "01sVC000000pl4vYAA",
        "01sVC000000pl6XYAQ"
      ]
    },
    "UnitPrice": 0
  }
]